### ISSUE TITLE
프로젝트 내 1차 역할 배분

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#1]
**[ 프로젝트 1차 목표 ]**
- GUI 구현 ( 메인 화면, 내역, 통계, 자산, 설정 화면 )
- 통계 및 자산 화면에서 보여줄 소비 성향 분석 및 소비 플랜 제시 내용 구성

각각 원하시는 GUI 구현 파트를 적어주시고 메인 화면을 담당하시는 분은 내용 구성쪽의 사전 작업을 해주시면 됩니다!

**Comment by wogur0915** [comment]
수입 내역과 지출 내역을 기입하고 수정(삭제)가능한 윈도우를 구현 할 예정입니다.

**Comment by KorBasilion** [comment]
안드레이는 메인 화면, 나머지를 제가 작업하는 것으로 진행하겠습니다.
