### ISSUE TITLE
내역창 정렬 구현 예정

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#100]
내역창의 head 를 클릭하였을 시에 날짜, 수입지출여부, 카테고리별 등으로 정렬되는 것을 구현하려고 관련 정보를 찾고있습니다.

https://stackoverflow.com/questions/32051780/how-to-edit-the-style-of-a-heading-in-treeview-python-ttk

https://stackoverflow.com/questions/61105126/tag-configure-is-not-working-while-using-theme-ttk-treeview

혹시 추가적인 정보를 알고계시다면 코멘트 주시면 감사드리겠습니다.

**Comment by Andrewendlesss** [comment]
https://ifelse.info/questions/7415/sort-treeview-columns - This is probably what you are looking for. Each column can be sorted by clicking on its head.

**Comment by wogur0915** [comment]
https://github.com/KorBasilion/OSS-Basic-Project/commit/a3ece72e550b2d7421952a54dc080a0807f697f8
정렬 구현 완료하였습니다. 답변감사합니다.
