### ISSUE TITLE
saveFile() 함수 설명 부탁합니다.

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#102]
```
def saveFile():
    f = asksaveasfile(mode="w", defaultextension=".csv",initialfile="house_hold_data.csv" , filetypes=(("CSV 파일", "*.csv"), ("All Files", "*.*")))
    if f is None:
        return
    wr = csv.writer(f)
    wr.writerow(["날짜", "수입/지출", "금액", "카테고리", "비고"])
    for i in range(len(dates)) :
        if dates[i] != None :
            wr.writerow([dates[i], expOrInc[i], money[i], types[i], otherDetails[i]])
    f.close()
```

What is the use of **CSV** and * here? Thank you

**Comment by wogur0915** [comment]
CSV는 엑셀의 형태로 출력 해주는 모듈 이자 파일 형식입니다.
* 은 어떤것을 여쭤보는지 모르겠네요

**Comment by Andrewendlesss** [comment]
*는  "*.csv", 그리고 ("All Files", "*.*")에서 어떤 작업을 하는지 궁금합니다.

**Comment by Andrewendlesss** [comment]
`"*.csv"), ("All Files", "*.*")))`

**Comment by wogur0915** [comment]
> _는 "_.csv", 그리고 ("All Files", "_._")에서 어떤 작업을 하는지 궁금합니다.

.csv 는 기본 확장자 명을 지정해 준 것 입니다.  ("All Files", "_._") 는 csv 외에 다른 확장자 파일을 선택할떄 나오는 부분입니다. (사용자가 원하는 형식으로 자유롭게 저장이 가능해요)

저장 버튼 눌러보시면 보이실겁니다.

**Comment by Andrewendlesss** [comment]
아하 알겠습니다! 감사합니다.
