### ISSUE TITLE
날짜 값 버그

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#104]
날짜는 yyyy-mm-dd로 나오는 버그가 있습니다. 해결해주시기 바랍니다.

<img width="844" alt="Screen Shot 2022-06-03 at 9 59 57 PM" src="https://user-images.githubusercontent.com/84678937/171859738-93bfbd5e-628a-4acf-8e3d-efe070d054a0.png">
.

**Comment by Andrewendlesss** [comment]
그리고 금액도 "숫자만 입략해주세요"라는 버그가 있습니다. 둘다 해결해주시기 바랍니다.

**Comment by wogur0915** [comment]
https://github.com/KorBasilion/OSS-Basic-Project/commit/a42ad673136485de81161c96365b8cdc2d6f7e62

해당 버그 확인 후 모두 수정 완료하였습니다.
