### ISSUE TITLE
원 뿐만 아니라 다른 종류의 통화를 추가하기가 필요

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#13]
I believe it would be a good idea to add different types(such as $ or EUR) of currencies to our program and let the user decide which one she/he would prefer to use. Then, do calculations and planning depending on the currency the user chose. 
So, how many and what type of currencies would you like for our program to have?
(의견은 한국어와 영어로 써주셔도 됩니다)

**Comment by wogur0915** [comment]
다른 통화를 추가 하는 것은 좋지만 프로그램의 특성상 매일, 실시간으로 변하는 환율을 적용시키기엔 무리가 있을 것 같다는 생각이 듭니다.

**Comment by KorBasilion** [comment]
사용성을 확장시키는 것은 좋으나 실시간 환율 적용이 어렵다는 점, 메뉴 구성이나 별도 아이콘, 로고가 이미지로 작업되기 때문에 각 단위에 맞춰서 진행하는 것에 한계가 있다는 점이 있어서 어려울 것 같습니다.
해당 부분은 이후 최종 발표 때 한계점에 포함하도록 하겠습니다.

**Comment by Andrewendlesss** [comment]
알겠습니다.
