### ISSUE TITLE
통화를 다른 통화로 환산하는 기능

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#14]
I think transferring the result from currency to another currency that the user chooses after he sees the final result would be a good idea. For example, if the user chooses $, then, after he sees the result and plan, he decides to change the currency($) to won, our program would automatically convert the result from $ to won depending on the current exchange rates.
What do you think? If you agree, how would you implement it? 
(의견은 한국어와 영어로 작성해주셔도 됩니다)

**Comment by wogur0915** [comment]
다른 통화를 추가 하는 것은 좋지만 프로그램의 특성상 매일, 실시간으로 변하는 환율을 적용시키기엔 무리가 있을 것 같다는 생각이 듭니다.

**Comment by KorBasilion** [comment]
재혁님 의견과 동일하게 실시간으로 환율을 적용할 수 있다면 가능하지만 현재 진행중인 프로젝트 내에서 실시간 환율까지 적용해서 기능을 구현하기에는 무리가 있다고 생각됩니다.

**Comment by Andrewendlesss** [comment]
알겠습니다!
