### ISSUE TITLE
데이터 저장 방법

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#15]
기능 내에서 사용하는 변수들을 어떤 방식으로 저장할 것인지 논의가 필요합니다.
현재 Pandas를 활용해 csv로 하는 방안과 피클을 사용하는 방안을 생각중인데 각자 의견 부탁드립니다.

**Comment by wogur0915** [comment]
찾아보니 csv로 하는 방법도 괜찮은 것 같습니다. stackoverflow 를 참고해보니 csv의 저장 및 불러오기 와 관련된 내용은 있지만 불러왔을 때 해당 데이터들이 프로그램 내 변수에 적용되는지 여부는 아직 파악이 되지 않았습니다. 테스트를 통해 좀 더 알아보겠습니다.

**Comment by KorBasilion** [comment]
데이터 저장은 csv로 확정을 하되, 필요할 경우 pandas도 활용하는 것으로 결정
