### ISSUE TITLE
프로젝트 내 2차 역할 배분

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#16]
[ 프로젝트 2차 목표 ]
5/28까지 최소 베타버전 완성 및 안정화
남은 한 주는 버그 픽스 및 README 작업 진행

[ 작업 필요 내용 ]
GUI 기능 구현 ( 내역, 통계, 자산 )
설정 내 기능 기획 및 GUI 작업

확인하셨으면 각각 진행하시는 구현 파트를 적어주시길 바랍니다!

**Comment by wogur0915** [comment]
내역 탭에서의 내역창, 내역추가창, 삭제창 (버튼) 을 구현 하겠습니다.

**Comment by Andrewendlesss** [comment]
설정 내 기능 기획 및 GUI 구현 하겠습니다.

**Comment by KorBasilion** [comment]
통계 및 자산 화면의 전반적인 기능 작업을 진행하겠습니다.
