### ISSUE TITLE
메인 브랜치에 머지할 때 잔여파일 여부

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#18]
제가 작업중이던 historyframe 브랜치 에는 사전에 작업하던 historyframe.py 파일과 mainview.py 파일 두 개가 존재합니다.
현재 작업상황은 historyframe.py 에서 진행하던 화면구성을 mainview.py 파일의 메인화면의 내역 프레임에 얹어 놓았고 이후 수정 작업 까지 마쳐 놓은 상황입니다.
feature_historyframe 브랜치를 그대로 main 브랜치에 merge 하게 될 경우 mainview.py 파일과 historyframe.py 파일 두 개 모두 main 브랜치에 존재하게되는데 백업을 위하여 남겨둔 채로 merge할지, 아니면 깔끔한 작업을 위해 histroyframe.py파일을 삭제 후 머지할지
의견 주시면 감사드리겠습니다.

추가로 두파일 함께 메인에 머지한 후 프로젝트 마무리단계에서 완성파일을 제외한 나머지 잔여파일을 삭제시키는 방법도 있습니다.

**Comment by KorBasilion** [comment]
historyframe.py 파일은 별도 로컬 머신에만 저장해두시고 레포 내에는 따로 올리지 않는 방향으로 하면 될 것 같습니다.

**Comment by wogur0915** [comment]
> 

그럼 브랜치내에서 historyframe.py 삭제후 메인에 머지요청 드리면 될까요?

**Comment by wogur0915** [comment]
프레임 작업 완료로 머지요청 드렸습니다.
