### ISSUE TITLE
소비 카테고리 넘버링

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#19]
사용하기로 결정된 소비 카테고리를 문자열 형태로 구분하는 것보다 넘버링을 부여하여 관리하는 것이 좋을 것 같아 의견을 여쭙고자 합니다.

예)
식비: 0
교통비: 1
등등

확인 후에 넘버링 관련해서 의견 부탁드립니다.

**Comment by wogur0915** [comment]
넘버링을 하게되면 사용자에게도 보여지는 것도 숫자로만 표기가 되는 건가요?

**Comment by KorBasilion** [comment]
아뇨 코드 내부에서만 넘버링된 값으로 관리하고 사용자가 보는 화면에는 본래 카테고리명으로 표기된다고 보시면 됩니다.
예를 들어변수 catagoryNum이 있다고 치면 해당 값이 0일 때 화면에 식비가, 1일 때 교통비가 나오도록 구성한다고 생각하시면 될 것 같습니다.

**Comment by KorBasilion** [comment]
넘버링을 해서 관리하는 것보다 str 형식 그대로 관리하는 것이 더 간단할 것으로 판단되어 별도 넘버링은 없는 것으로 하겠습니다
