### ISSUE TITLE
병합 과정에서의 코드 가독성

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#21]
별도 분할 없이 한 파일 내에서 모든 코드를 작성하려니 코드의 길이가 길어서 코드 가독성이 매우 떨어지는 상황입니다.
혹시 상관 없으시다면 한 파일 내에서 관리하는 게 아니라 파일을 분할해서 관리하는 건 어떠신가요?
파일 분할한 코드는 제가 작업해서 제공해드리겠습니다.

**Comment by wogur0915** [comment]
넵 저도 시도해봤습니다만 생각보다 쉽지않아서 가능하시면 부탁드리겠습니다

**Comment by KorBasilion** [comment]
관련해서는 기능 구현 이전에 작업해서 레포에 올리도록 하겠습니다.
