### ISSUE TITLE
설정 의견

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#27]
I've thought about what should I add to settings and this is what I came up with:
언어
도움말
테마 - 여러 가지 색갈
글자 크기
기본 통화(not sure yet)
환율 직접 설정
I want to hear your opinions about this. Also, if you have anything to add, then feel free to write down your opinion.

**Comment by KorBasilion** [comment]
해당 내용 중에서 프로그램에 맞춰 작업할 수 있는 부분은 도움말 정도밖에 안 될 것 같습니다.
언어, 테마, 글자 크기의 경우, 일부 로고나 버튼이 이미지 상태로 제공된다는 점때문에 구현 불가하고 통화 단위는 사전에 말씀드린 대로 구현에 어려움이 존재합니다.

**Comment by wogur0915** [comment]
데이터 저장 및 불러오기 관련한 메뉴를 설정 탭에 넣는건 어떨까요?
아니면 상단에 메뉴바를 추가하여 구성하는것도 괜찮을 것 같습니다.

**Comment by Andrewendlesss** [comment]
알겠습니다. 주의하겠습니다!
