### ISSUE TITLE
현재 구현 상황 파악

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#28]
현재 작업하시는 내용이 어느 정도까지 작업이 진행되었는지 해당 이슈에 남겨주시길 바랍니다

**Comment by KorBasilion** [comment]
추가로 남아있는 이슈 중에 의견 요청드렸던 내용들 의견 달아주시길 바랍니다

**Comment by wogur0915** [comment]
https://github.com/KorBasilion/OSS-Basic-Project/issues/34#issue-1244298415
참고 바랍니다.
#34
