### ISSUE TITLE
프로젝트 화면 별 상세 구현 내용

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#3]
각 화면( 내역, 통계, 자산, 설정 )에 어떤 기능을 구현할 것인지 상세 구현 내용을 정해야합니다!

기본적으로 가계부 작성, 소비 통계 제공, 소비 플랜 제시 기능이 필요하고 이 외에 필요한 기능이 있으면
추가로 의견 부탁드립니다!

**Comment by wogur0915** [comment]
가계부 내역 작성 화면에서는 날짜, 수입/지출 여부 선분류, 카테고리(분류 선택), 금액, 비고(메모 내용)  등으로 이루어진 입력창과 입력된 데이터를 기반으로한 내역 표시창을 구현할 생각입니다.

**Comment by Andrewendlesss** [comment]
가계부 메인화면은 내역, 통계, 자산, 설정 버튼을 구현하고 그 버튼 느루면 새 윈도우(수입/지출, 자산, 등등) 나오게 구현할 생각입니다.

**Comment by KorBasilion** [comment]
통계 화면은 해당 사용자의 소비 성향과 소비가 가장 많았던 상위 5개의 카테고리를 보여주는 방향으로 구현할 예정입니다.
또한 자산 화면은 현재까지의 소비와 지출을 합친 합계와 각각 소비, 지출의 합, 해당 자료를 토대로 소비 플랜을 제시해주는 내용을 보여줄 예정입니다.

설정 화면의 경우, 어떠한 기능을 추가할지 미정되었기에 추가 논의가 필요합니다.
