### ISSUE TITLE
파일 분리 작업 머지 요청

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#32]
1차적인 분리 작업을 마쳤고 작업 상황을 봐서 분리가 필요할 경우, 추가 작업을 진행하겠습니다.
분리한 내용은 머지 요청을 올려놨으니 확인 후 머지 부탁드립니다

**Comment by KorBasilion** [comment]
현재 분할 작업 확인 과정에서 문제가 확인되어 재검토중입니다.

**Comment by KorBasilion** [comment]
재검토 완료 및 머지 요청 완료

**Comment by wogur0915** [comment]
분할 파일들을 제가 vs code로 실행해 보았을 때 실행은 잘되었는데
![image](https://user-images.githubusercontent.com/34836246/169704503-ddcbff21-8e6d-4be1-a6c2-078d7c9764aa.png)

위와같이 노란 밑줄이 생기는데 문제 없는게 맞는건지 검토한번 부탁드려요

**Comment by KorBasilion** [comment]
에디터 내에서 어떤 경고문이 뜨면서 밑줄이 생기는지 제시 부탁드립니다.
Python IDLE 에디터로 확인했을 때는 별도 문제가 없다고 뜨네요.

**Comment by wogur0915** [comment]
다른파일로 새로수정해보니 밑줄이안나오네요 
"PhotoImage" is not definedPylance[reportUndefinedVariable](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

실행은잘되는데 밑줄에 가져다대면 저런 문구가나와서 다른 파일들에 붙여넣기해보니 정상적으로 나와 머지승인하겠습니다.
