### ISSUE TITLE
현재 진행상황 보고 및 의견 수렴

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#34]
내역 파트 진행상황 전달드립니다.
일단 계획하였던 내역 추가와 삭제 기능까지 구현하였으며
수입 / 지출 선택 여부에 따라 카테고리 콤보박스를 가변적으로 나타나게 까지 구현 예정이며 머지상황 및 파일 분할 관련하여 커밋이 덜된 관계로 아직 커밋 이전 상태입니다.

![image](https://user-images.githubusercontent.com/34836246/169704770-eb5fdda0-4be7-414a-af4e-506eb6cb3641.png)
![image](https://user-images.githubusercontent.com/34836246/169704782-f46503f2-a81a-4919-9a0a-4e3c77d1c9b5.png)

한가지 우려 되는점은 내역을 삭제할 때 또한 입력 할때와 동일한 방법으로 입력했던 내역을 그대로 사용자로부터 입력을 받으면 삭제 되게끔 구현을 해놓았는데 기능상으로는 문제가 없긴 하지만 사용자가 느끼기에 다소 불편 할 수 있다고 생각되어 행을 더블 클릭 시, 내용이 자동으로 입력된 삭제창을 구현할 수 있으면 하려고 하는데 어떻게 생각하는지 여쭙습니다.
시간관계상 진행이 어려울 수도 있습니다.

**Comment by KorBasilion** [comment]
삭제 기능의 경우, 추가 화면처럼 입력해서 삭제하는 게 아니라 트리 리스트에서 따로 선택해서(체크 박스 구현 혹은 마우스 선택) 삭제하는 기능으로 구현하는 것이 좋을 것 같습니다.
삭제할 내용을 입력하고 해당 내용과 일치되는 값을 삭제할 때, 값이 다르면 오류가 나는 부분도 처리해야하기 때문에 처음 구현 자체를 위와 같이 구현하는 것이 맞는 것 같습니다.

**Comment by wogur0915** [comment]
알겠습니다. 일단 분할 파일 머지후 현재진행상황까진 커밋해놓은 뒤에 기능 수정하도록 하겠습니다.

**Comment by wogur0915** [comment]
관련 내용 이슈로 다시 올렸습니다.
https://github.com/KorBasilion/OSS-Basic-Project/issues/46
