### ISSUE TITLE
코드관련 질문 있어서 이슈 남깁니다. 버튼 클릭 command 관련.

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#35]
병합하신 코드를 보니 command=lambda:[addList(treeview)] 이런식으로 람다를 이용하여 구성하셨던데 저렇게 하는 이유가 있는건가요?

**Comment by KorBasilion** [comment]
기존에 Command를 통해 사용자 정의 함수를 실행하실 때는 별도 매개변수가 없었기 때문에 상관 없었지만 분할 과정에서 매개변수 처리가 생겼습니다.
때문에 매개변수를 포함한 상태로 함수 실행을 구현하기 위해 람다 표현을 사용했습니다.

**Comment by wogur0915** [comment]
이해 되었습니다. 설명 감사합니다.
