### ISSUE TITLE
통계, 자산 화면의 로고 변경 로직

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#37]
작업중인 통계, 자산 화면의 로고가 변경되도록 설정하는 기초 로직을 제작하고자 합니다
- 내역에서의 값이 변경될 때마다 해당 값을 반영하여 로고가 바뀌어야함
- 각각 다른 이미지 파일이 적용되도록 사전 설정 필요

**Comment by wogur0915** [comment]
통계 자산화면의 로고가 변경된다는 것이 어떤의미인지 이해하지 못했습니다..

**Comment by KorBasilion** [comment]
제가 작업중인 화면의 로직이고 각각의 로고는 성향, 플래닝 제시 로고입니다
