### ISSUE TITLE
내역 내에서의 데이터를 활용한 가공 변수 요청

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#38]
통계, 자산 화면의 기능 구현에 있어 내역 화면에서 받아들인 데이터를 가공한 값이 필요합니다.
필요한 값은 수입 총합, 지출 총합, 각 카테고리별 소비 금액(어떤 카테고리의 소비 금액인지도 확인 가능해야함) 입니다.

**Comment by wogur0915** [comment]
알겠습니다. 참고하여 빠른시일 내에 커밋하도록 하겠습니다.
