### ISSUE TITLE
머지관련 질문있어서 드립니다.

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#39]
현재 로고 브랜치 에서 작업중이신데 제가 historybackend 브랜치에서 동시 작업중입니다.
이런 경우에 머지는 어떻게 해야하는지 궁금합니다.
개인적으로 repo를 생성하여 테스트를 해보았는데 conflict가 날 것같아 방법을 아시는지 여쭈어보아요

**Comment by wogur0915** [comment]
해당 코드 불일치로 인한 conflict 문제 해결을 위해 logo_function 브랜치와 histroybackend 브랜치의 코드 일치화 작업을 진행하였습니다.
작업의 엇갈림 방지를 위해 작업전 메인 브랜치의 코드보다 더 진행된 (메인에 머지하기 전인) 다른 브랜치가 있다면 해당 브랜치를 작업하실 브랜치로 pull request 하신 후 작업해주시면 감사드리겠습니다.

**Comment by KorBasilion** [comment]
다른 파일에서 각자 작업하는 것이 아니고 동일한 파일 내에서 서로 다른 기능을 구현하고 있기 때문에 conflict는 계속 발생할 수 밖에 없습니다.
저희 작업 방식 자체가 서로 같은 파일을 공유하는 것이기 때문에 해당 부분은 아예 파일을 전체 분할하지 않는 이상 해결 불가능하다고 보시면 됩니다.
때문에 main 브랜치로 먼저 머지한 인원이 있으면 해당 내용을 Pull해서 각각 브랜치에서 conflict를 해결하시면 됩니다.

**Comment by KorBasilion** [comment]
추가로 작업 중인 브랜치에 커밋하실 때는 말 없이 하시지 마시고 사전에 말씀 부탁드립니다

**Comment by wogur0915** [comment]
알겠습니다 주의하겠습니다.
