### ISSUE TITLE
설정 GUI

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#42]
I'm going to create a new branch specifically dedicated to 설정. Then, I'm going to start working on how that part's GUI. I've already thought of a specific design. However, I'd like to hear your opinions first.

**Comment by KorBasilion** [comment]
일단 설정 화면 내에 어떤 기능을 넣을 건지에 따라 화면 구성이 달라질 것 같습니다

**Comment by Andrewendlesss** [comment]
알겠습니다.
