### ISSUE TITLE
설정에 있는 "도움말" 무슨 내용 들어가는지 의견

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#43]
I'm still thinking about what to add to our 설정 part. However, in my last closed issue we already decided on 1 thing that will be there for sure. It is "도움말". So, I'd like to know your opinions on what the user would need if he has difficulties using our program.

**Comment by wogur0915** [comment]
개발자에게 문의 할 수 있도록 개발자 이메일 정도 label형태로 넣으면 좋을 것 같습니다.

**Comment by KorBasilion** [comment]
기본적인 프로그램 사용법 정도가 들어가면 될 것 같습니다

**Comment by Andrewendlesss** [comment]
알겠습니다.
