### ISSUE TITLE
프로그램 명칭 정하기

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#47]
제작하는 프로그램의 명칭을 정해서 관련된 디자인 및 윈도우 명칭을 수정해야 합니다.
프로그램 명칭에 대한 자유로운 의견 부탁드립니다!

**Comment by wogur0915** [comment]
Money Coach (머니코치) 어떤가요

**Comment by KorBasilion** [comment]
해당하는 이름이 좋을 것 같네요!
이에 맞춰서 작업 진행하겠습니다
