### ISSUE TITLE
파일 분할 과정에서의 파라미터 오류

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#49]
더블클릭 삭제 기능을 가진 함수를 구현한 후 분할된 형식에 맞게 적용 도중 이벤트를 파라미터로 가져오는 함수가 treeview 를 파라미터로 불러오지 못하여 정상 동작하지 않는 현상이 발생되는 것이 파악되었습니다.

람다 형식을 이용하여 이벤트를 파라미터로 받아오면서 treeview 또한 받아오는 방법을 찾아보겠습니다.

**Comment by KorBasilion** [comment]
treeview.bind로 이벤트 받으시고 해당 이벤트로 함수 실행하시려면 일반 람다형식 말고 lambda event:[Function(event, parameter)]와 같은 형식으로 작성하시면 오류 해결 가능합니다

**Comment by wogur0915** [comment]
> treeview.bind로 이벤트 받으시고 해당 이벤트로 함수 실행하시려면 일반 람다형식 말고 lambda event:[Function(event, parameter)]와 같은 형식으로 작성하시면 오류 해결 가능합니다

답변감사합니다. 확인 후 수정하여 이상없을 시 커밋 진행하도록 하겠습니다.

**Comment by wogur0915** [comment]
https://github.com/KorBasilion/OSS-Basic-Project/commit/0afd550c433685bf3c1ce88f6f7ec5b85174b0a0

의견을 반영하여 코드 수정 진행하였습니다.
