### ISSUE TITLE
프로그램 파일 분할 방식

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#5]
프로그램한 코드 전체를 하나의 코드 파일로 묶어서 관리할 것인지, 별도 파일을 나누어 모듈화된 방식으로 관리할 것인지 정하고자 합니다!
관련해서 의견 한 번씩 적어주시길 바랍니다.

**Comment by wogur0915** [comment]
깔끔하게 모듈 방식으로 해보려고 하였으나 변수선언과 같은 부분에 있어서 불러오는데에 다소 오류가 있어 수정하며 진행해보고 있습니다. 제대로 동작이 안된다면 하나의 코드 파일로 묶어서  관리해야 할 것 같네요

**Comment by KorBasilion** [comment]
파일 분할 방식은 이후 회의를 통해 확정짓도록 하겠습니다.

**Comment by KorBasilion** [comment]
파일 분할 방식은 회의 결과 별도 분할 없이, 한 파일에서 작성하는 것으로 확정되었습니다.
