### ISSUE TITLE
설정에 있는 "about us (개발자들 소개)" 무슨 내용 들어가는지 의견

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#52]
I would like to know what would you like for the users to know about you and our team. Write down your brief self-introduction or whatever you want the user to know about the developers of this program(us) in KOREAN or EN(상관 없습니다).

**Comment by KorBasilion** [comment]
설정 부분에 개발자에 대한 소개는 별도로 필요 없을 것 같습니다
해당하는 부분은 README 파일쪽에서 보여주면 될 것 같네요

**Comment by Andrewendlesss** [comment]
I think it would be a good idea if the user could access info about the developers from the program with just 1 click rather than going to our GitHub and trying to find who we are. For casual users, it would be inconvenient to say the least, so I'm going to make the job of finding the info about us by just adding 1 additional button in settings at the very end.

**Comment by KorBasilion** [comment]
설정을 더보기로 바꾸는 것에 따라 개발자에 대한 소개는 간략하게 넣는 것으로 하겠습니다
