### ISSUE TITLE
new window 여는 함수

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#58]
`def openNewWindow(info):
    newWindow = Toplevel()
    newWindow.title("Help")
    newWindow.grid
    Label(newWindow, text = info, fg = "red").pack()`
the "info" parameter takes a text that you want the new window to have.
For example:
`text2 = "We are CBNU students"
Us = Button(settingFrame, image=test, text="About Us", width=388, height=50, compound="c", fg="dark green", command = lambda : openNewWindow(text2))`
The result: when you click Us button, the new window opens with a text defined in a text2 variable.

**Comment by KorBasilion** [comment]
해당하는 내용은 이슈가 아니라 단순히 커밋 메시지로 올려두시면 될 것 같습니다

**Comment by Andrewendlesss** [comment]
It'd be a very big message then!:) I think this information and the issue(documentation) before should be added in README file because this could be confusing for some people.
