### ISSUE TITLE
화면별 아이콘/로고 제작

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#6]
프로그램 전반에 사용될 아이콘, 버튼 사진, 메인화면 로고 등의 제작이 필요합니다.
관련 작업은 포토샵으로 작업을 진행하는 것으로 하고 디자인쪽 관련해 의견이 있으시면 말씀 부탁드립니다!

**Comment by wogur0915** [comment]
버튼같은 경우 추가는 +에 겉에 동그라미가 둘러싼 형태로, 삭제는 -에 겉에 동그라미가 둘러싼 형태로 하였으면 좋겠고
내역 버튼은 내역이라는 글씨와 함께 document 아이콘을,  통계버튼은 통계라는 글씨와함께 그래프모양 아이콘을, 자산은 돈모양을, 그리고 설정은 톱니바퀴 아이콘을 함께하여 만들면 좋을 것 같습니다.
메인화면 로고 같은 경우 충북대 마스코트인 우왕이를 섞으면 어떨까요

**Comment by KorBasilion** [comment]
각 버튼은 알맞은 아이콘이 있는지 확인해보고 해당 의견을 반영해보도록 하겠습니다.
메인화면 로고의 경우, 우왕이 자체를 활용한 디자인이 어떻게 될지 모르겠어서 고려는 해보되 활용이 가능할지에 대한 여부는 애매할 것 같습니다.
