### ISSUE TITLE
파일 저장 메뉴와 불러오기(열기) 메뉴 추가와 관련하여 의견 여쭙습니다.

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#60]
CSV파일을 통해 가계부 내역을 저장하고 불러오는 과정에서 따로 버튼을 만드는 것이 아닌
![image](https://user-images.githubusercontent.com/34836246/170861616-92a77fd7-bf9c-4bda-b21a-bbdec69fa23c.png)

위와같은 메뉴바를 추가하여 진행해보려 하는데 의견 여쭤봅니다.

**Comment by KorBasilion** [comment]
현 작업 상황에서 해당하는 부분을 구현해서 넣기에는 시간적 여유가 없을 것 같습니다

**Comment by wogur0915** [comment]
제가 지금 csv 저장 및 불러오기 작업을 테스트 하면서 메뉴바도 가능하면 해보려고 하고 있습니다.
그럼 혹시 저장 및 불러오기를 어떻게 할 지 의견이 있으신가요?

**Comment by KorBasilion** [comment]
기본적으로 프로그램을 실행하면 기존에 사용하던 데이터가 있을 경우, 자동으로 불러오는 형식을 사용하고 저장은 데이터의 변동이 일어날 때마다 해주는 것으로 하면 될 것 같습니다
데이터의 초기화가 필요할 경우에는 설정에서 별도로 데이터 초기화가 가능하도록 세팅하면 될 것 같고요

**Comment by wogur0915** [comment]
알겠습니다. 피드백 참고하여 구현 해보도록 하겠습니다.
