### ISSUE TITLE
Currency converter 설정에 추가할 예정

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#61]
I've tried to create a currency converter and thought about how we should implement it. So, there will be a button named "currency converter" and it will open a window with a program that converts won to other currencies. However, since we can't implement real-time currency function, I decided to either:
1. Let the user put it himself or 
2. Just use the current currency(2022.05.30~) and let the user know from which date the current state of currency is. So, which option do you prefer more?
P.S: This is just an additional feature that is NOT connected to 입출/통계/자산. So don't worry, there will be no bugs/errors when merging. 
<img width="398" alt="Screen Shot 2022-05-29 at 9 11 24 PM" src="https://user-images.githubusercontent.com/84678937/170867655-f3c66791-176e-408d-9a81-1a7506bf8f69.png">
<img width="404" alt="Screen Shot 2022-05-29 at 9 12 14 PM" src="https://user-images.githubusercontent.com/84678937/170867659-40db1b2b-b5af-4037-8f4d-04cc67e14a09.png">

**Comment by wogur0915** [comment]
확인하였습니다.

**Comment by Andrewendlesss** [comment]
명심하겠습니다. 혹시 다른 의견이 있으세요?

**Comment by Andrewendlesss** [comment]
I'm going to think about how to implement that function that lets the user choose his own currency by writing it down. If possible, I'm going to complete it till Friday, If not, then I'm going think about something else.
다른 의견의 없어서 이슈를 닫겠습니다.
