### ISSUE TITLE
설정에 있는 "version"

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#62]
I decided to put "version" info in settings. So, my question is, what version number our program should have(for example: 1.0, 0.1, 0.01, BETA, ALPHA etc...)?

**Comment by wogur0915** [comment]
0.1.0 beta 가 어떤가요

**Comment by Andrewendlesss** [comment]
좋습니다. 그 이름으로 하겠습니다. 감사합니다.
