### ISSUE TITLE
오픈소스라이선스는 설정에 넣어야 되는지 의견

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#63]
Should I add Open-Source-Licence that we use and its information into our setting part?

**Comment by wogur0915** [comment]
넣게되면 어떤 걸 넣으시려는거죠?

**Comment by Andrewendlesss** [comment]
저희 라이선스 종류 + 그 라이선스의 간단한 설명 + 라이선스의 링크.
