### ISSUE TITLE
내역 창에서 더 추가할 부분이나 고쳤으면 하는 점이 있는 지 피드백 부탁드립니다.

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#64]
제 hsitoryBackEnd 브랜치 를 참고하셔도 되지만 캡쳐도 첨부해 봅니다.
![image](https://user-images.githubusercontent.com/34836246/170928958-bd9aa8ca-fc92-471a-ba62-fd6c075f5ced.png)

현재 내역창에서 가계부 추가 윈도우를 통한 데이터 추가 및 프로그램 내에서 보여주는 treeview 구현 완료 하였으며
삭제 기능 또한 삭제를 원하는 행을 더블 클릭하여 disabled 된 (수정 불가처리) 가계부 삭제 윈도우를 띄운 뒤 확인 버튼을 누르면 삭제 경고가 뜨게되고 추가로 한번더 삭제를 누르면 삭제되는 방식으로 구현되어 있습니다.

추후 통계에서 쓸 수 있도록 각 카테고리별 수입 지출의 합계 함수 또한 구현 완료하였습니다.
버튼 배치는 저번 회의 피드백에 따라 변경 할 예정입니다.

추가로 질문사항이나 변경 요청건 있으시면 코멘트 주세요.

파일입출력 작업 까지하여 마무리할 예정입니다.

**Comment by Andrewendlesss** [comment]
What do you think about adding a function(move up, move down) to let the user change the order of his 수입/지출?

**Comment by wogur0915** [comment]
> What do you think about adding a function(move up, move down) to let the user change the order of his 수입/지출?

행의 위치를 바꾸는것을 말하는건가요? 아니면 정렬을 말하는건가요?

**Comment by Andrewendlesss** [comment]
정렬 - 자동으로 작동됩니다.
행위 위치 - 수동으로 바꿀 수 있습니다. 
이렇게 하면 어떨까요?

**Comment by KorBasilion** [comment]
삭제버튼 누르면 입력창과 동일한 형식의 창이 뜨는 게 아니라 바로 삭제하시겠습니까?를 묻는 창이 뜨면 좋을 것 같습니다

**Comment by wogur0915** [comment]
> 삭제버튼 누르면 입력창과 동일한 형식의 창이 뜨는 게 아니라 바로 삭제하시겠습니까?를 묻는 창이 뜨면 좋을 것 같습니다

https://github.com/KorBasilion/OSS-Basic-Project/commit/2e56160e37d73b392c187c8f8be8e7a5c55bcff5
반영하여 커밋하였습니다.
