### ISSUE TITLE
A hint for the user if a button has no text function

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#68]
I think it would be a good idea to add a hint in the form of a pop message when the user's mouse Is hovering over buttons with no text( for example, +)

![Pg4KF](https://user-images.githubusercontent.com/84678937/170987593-4ccd0408-4441-4cb1-9ee5-f1618cf83ebc.png)

What do you think?

P.S If you don't have time to implement this feature, then I can help with it.

**Comment by wogur0915** [comment]
좋은생각인 것 같은데 관련 코드나 자료 올려주시면 참고하겠습니다.

**Comment by Andrewendlesss** [comment]
넵 알겠습니다.

**Comment by Andrewendlesss** [comment]
import tkinter as tk

class LikeThis(tk.Frame):
    def __init__(self, *args, **kwargs):
        tk.Frame.__init__(self, *args, **kwargs)
        self.l1 = tk.Label(self, text="Don't press it!")
        self.l2 = tk.Label(self, text="", width=40)
        self.l1.pack(side="top")
        self.l2.pack(side="top", fill="x")

        self.l1.bind("<Enter>", self.WhenTouch)
        self.l1.bind("<Leave>", self.WhenLeave)

    def WhenTouch(self, event):
        self.l2.configure(text="Hello world")

    def WhenLeave(self, enter):
        self.l2.configure(text="")

if __name__ == "__main__":
    main = tk.Tk()
    LikeThis(main).pack()
    main.mainloop()

**Comment by wogur0915** [comment]
위 사진처럼 노란 박스의 힌트가 나오는 코드가 궁금합니다..

**Comment by Andrewendlesss** [comment]
The image above I found on the internet!
However, after doing some research, I found this simple code that does the same thing! However, you need to install additional side-package to make it work.

```
from tkinter.tix import *
from tkinter import *

win = Tk()
win.geometry("400x200")
tip= Balloon(win)
my_button=Button(win, text= "Python", font=('Helvetica bold', 20))
my_button.pack(pady=20)
tip.bind_widget(my_button,balloonmsg="This")
win.mainloop()
```

**Comment by KorBasilion** [comment]
해당 기능은 필요한 부분에 한하여 적용하면 될 것 같습니다
