### ISSUE TITLE
add list 함수 관련 설명 부탁합니다.

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#69]
1) Can you please explain how does that function work? Thank you
<img width="675" alt="Screen Shot 2022-05-31 at 3 27 49 PM" src="https://user-images.githubusercontent.com/84678937/171107555-b9fd1e89-a76f-40fc-8c58-e14d6209003d.png">
.

**Comment by wogur0915** [comment]
이해가 되지 않는 부분이 어디이신지 말씀해주시면 알려드리겠습니다.

**Comment by Andrewendlesss** [comment]
Line 31: Why did you declare those variables as global?
Line 59: treeview.bind("<Double-1>", lambda event:[dbclickDelList(event,treeview)]) - I don't understand from where dbclickDelList function came from. I've searched it up on the internet but didn't find one.
Thank you!

**Comment by Andrewendlesss** [comment]
설명해주셔서 감사합니다!
