### ISSUE TITLE
A question regarding overall design

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#70]
I want to design "settings" to make it look as modern(ish) as possible. In order to do that, I have to use side-packages. Is it okay if I use side-packages to design **setting** part? Also, don't worry, those packages **will not affect your windows in any way!**

**Comment by wogur0915** [comment]
https://github.com/KorBasilion/OSS-Basic-Project/issues/73

Does the side package mean this?

**Comment by Andrewendlesss** [comment]
No. Side-packages are packages from external sources. For example customtkinter that looks like this
<img width="936" alt="Screen Shot 2022-05-31 at 6 30 32 PM" src="https://user-images.githubusercontent.com/84678937/171141862-ed794ea6-ab1d-4601-b8a4-1a22f8085e90.png">
.

**Comment by wogur0915** [comment]
Do you have a picture of thoughts in your head?

**Comment by KorBasilion** [comment]
디자인 자체를 이에 맞춰서 작업하기에는 시간상 무리일 것 같습니다
