### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#73]
This is just a rough draft of how the "settings" would look like. I still haven't utilized side design packages to make it look modern(I'm waiting for your approval in the last issue). I would have a total of 6 buttons settled in the middle. Our Github repository URL will be right at the bottom, and if the user touches the button(doesn't click it), then it becomes green and shows the user URL of our GitHub to indicate that by pressing the button - our GitHub link will be opened in his default browser. 
This is how it all looks like + converter( I haven't designed it yet)
<img width="1054" alt="Screen Shot 2022-05-31 at 6 15 29 PM" src="https://user-images.githubusercontent.com/84678937/171139916-12ad1f25-684e-49a2-b29a-cc1fc6a572c6.png">

<img width="833" alt="Screen Shot 2022-05-31 at 6 14 56 PM" src="https://user-images.githubusercontent.com/84678937/171139950-ee50743c-bd05-47db-bd8d-4fa9f323f818.png">

**Comment by Andrewendlesss** [comment]
I open the url in the user's default browser of his system by using the openURL() function of the webbrowser module and providing url link in it. So, it's the same as writing down the URL in your browser and visiting the web-site. Our GitHub repository doesn't require any separate permissions to see what is inside as far as I know!

**Comment by KorBasilion** [comment]
해당하는 부분은 전체적인 프레임 재구성이 필요한 것으로 확인되고 설정->더보기로 바뀌는 것에 따라 디자인 기획해서 조정하면 될 것 같습니다
