### ISSUE TITLE
파일/데어터 관리 설명 부탁합니다.

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#77]
I'm fairly new to python, so I'm curious how do you work with data on your branches? How do you accept data from the user and keep it on his/her computer? And then, how are you going to access that data in the future after the user closes->reopens the program?

**Comment by wogur0915** [comment]
I am making the function of open/save files.
Our program is going to open by File menu on menubar.
And save too

**Comment by Andrewendlesss** [comment]
Thank you !
