### ISSUE TITLE
function 파일의 분할이 좀 필요해 보입니다.

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#78]
제 브랜치에서 작업한 것들과 안드레이의 브렌치 그리고 희범 브랜치의 function.py 에있는 것들을 모두 머지할 경우 코드 분량이 상당하며 가독성도 좋지 않을 것으로 예상됩니다.
function 또한 history관련 function, setting function 등 기능별로 파일을 나누는 것은 어떨까요?

**Comment by Andrewendlesss** [comment]
Hmm, sounds like a good idea. I don't know if it will work though. I think we need to test it first before deciding

**Comment by wogur0915** [comment]
> Hmm, sounds like a good idea. I don't know if it will work though. I think we need to test it first before deciding

일단 머지를통해서 각자 완성한코드들을 하나로 합친 뒤에 분리하는 것이 좋을것으로 보입니다.

**Comment by KorBasilion** [comment]
이후 작업한 내용들 머지한 이후에 제가 분리 작업을 진행하겠습니다
