### ISSUE TITLE
mainView branch에서 1pixel.png 가 없어서 생기는 오류

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#8]
mainView branch 에 있는 가계부.py를 실행할 경우 1pixel.png 파일이 함께 존재하지 않아 실행이 되지 않는 오류가 있습니다. 확인 후 1pixel.png 파일을 branch 내에 추가하여 주시기 바랍니다.

**Comment by KorBasilion** [comment]
1pixel.png 파일의 경우, 각 버튼과 라벨들의 픽셀 단위 배치를 위해 추가한 임의 파일로 별도로 레포에 추가하지 않을 예정입니다.
이후 작업에서 별도로 취급 및 추가가 필요하다 판단된다면 추가 판단 후 파일을 추가하도록 하겠습니다.

**Comment by wogur0915** [comment]
알겠습니다. 확인하였습니다.
