### ISSUE TITLE
카테고리별 소비 성향 명칭

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#82]
'식비'
'주거/통신'
'의복/미용'
'건강/문화'
'교육/육아'
'교통/차량'
'기타'
해당 카테고리별로 소비 성향을 도출해줄 때 어떤 타이틀로 도출해줄지에 대한 의견이 필요합니다

**Comment by wogur0915** [comment]
식비 : 101번지 남산만한 배
주거/통신 : 하우스 러버 / 전화가 불타는 콜센터
의복/미용 : 길거리 패션 모델
건강/문화 : 튼튼이 헬스 Boy(Girl) / 환상의 나라 컬쳐 랜드
교육/육아 : 스터디 홀릭 열정펜 / 존경스런 부모님
교통/차량 : 동해번쩍 서해번쩍 홍길동

기타는... 뭐로할지 잘 모르겠네요..

**Comment by Andrewendlesss** [comment]
기타 : 평범하지 않은 사람

**Comment by KorBasilion** [comment]
별도로 타이틀 및 내용 구성해서 제작 완료
