### ISSUE TITLE
histroybackend 브랜치 머지 승인 이후 각자 코드 전체적 머지 요청 문의

### ISSUE THREAD

**Issue by wogur0915** [KorBasilion/OSS-Basic-Project#86]
현재 코드들이 각자 진행상황에 따라 많이 분산되어 있어 histroybackend 브랜치가 머지 된 이후에는 개인 커밋 진행이 아닌 현재까지 진행된 부분에 대해 메인 브랜치에 머지 부탁드리겠습니다.
아마 그냥 머지하려고하면 conflict 가 생길거라 메인에 머지된 코드를 기반으로 본인이 작업하신 내용 개인브랜치에 수정 커밋 하신 후 머지 해보시면 될겁니다.

전체적으로 작업자들 코드가 모두 머지가 된 이후에는 개인 커밋 계속진행하기 보다는 브랜치간의 최신 작업물에서 pull 계속 해가면서 하면 어떨까하는 생각합니다. 그러면 아마 conflict 없이 추가하는데에 번거로움이 없을거같아서요

**Comment by KorBasilion** [comment]
Conflict 해결하는 과정과 메인 브랜치에 있는 내용을 자신의 브랜치로 가져와서 수정 및 커밋하는 과정은 차이가 없어서 굳이 그렇게 안 해도 될 것 같기는 하네요
지금은 거의 마무리 단계이기도 하니 Conflict 발생하는 사항이 그리 많지도 않아 괜찮을 것 같습니다

**Comment by wogur0915** [comment]
알겠습니다.
