### ISSUE TITLE
삭제 window는 2번으로 나옵니다.

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#92]
double click 하면은 삭제 window는 한번 cancel 누르면 다시 나오는 문제 보입니다.

<img width="893" alt="Screen Shot 2022-06-02 at 9 47 37 PM" src="https://user-images.githubusercontent.com/84678937/171632679-d3c4e476-92cd-4c2b-b099-5c935b99fbaa.png">

**Comment by KorBasilion** [comment]
해당하는 오류는 MacOS의 문제인 걸로 확인됩니다

**Comment by Andrewendlesss** [comment]
이상하네요. 알겠습니다.
