### ISSUE TITLE
기존 통계/자산 화면에서의 주간 월간 변경

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#94]
기존 통계/자산 화면에서 주간/월간 데이터를 토대로 데이터를 분석하는 것을 전체/월간으로 바꿔서 진행하려고 합니다
누적된 자료에 대한 분석이 없어서 해당하는 방향으로 하는 게 좋을 것 같아 이렇게 하려는 건데 관련해서 의견 부탁드립니다

**Comment by wogur0915** [comment]
네 전체 월간으로 진행하는 것이 더 좋을 것 같습니다.

**Comment by KorBasilion** [comment]
해당하는 조정 내용에 맞춰 작업 완료했습니다
