### ISSUE TITLE
통계/자산 화면의 내역 변경 반영 로직

### ISSUE THREAD

**Issue by KorBasilion** [KorBasilion/OSS-Basic-Project#97]
내역이 추가, 삭제됨에 따라 통계/자산 화면의 내용도 바뀔 수 있도록하는 로직을 구현하도록 하겠습니다
- 내역에서 데이터가 추가/삭제되면 각 화면도 이를 반영하여 내용 변경
- 기존에 작업된 로고 변경 기초 로직을 활용하여 추가 작접 예정

**Comment by wogur0915** [comment]
알겠습니다

**Comment by KorBasilion** [comment]
작업 완료
