### ISSUE TITLE
Should I add this feature to our program?

### ISSUE THREAD

**Issue by Andrewendlesss** [KorBasilion/OSS-Basic-Project#98]
This feature gives a hint to the user in the form of a pop message. I think this is a great improvement of the user's experience! What do you think? If you agree with it, then I will add this to other windows as well but first I want to hear your opinions and agreement

https://user-images.githubusercontent.com/84678937/171772935-396fea26-0476-430c-8232-0a0a3acea7be.mp4

.

**Comment by KorBasilion** [comment]
관련해서는 힌트 메시지 구현 없이 진행하는 것으로 확정되었습니다
